ALTER TABLE lancamentos
    ADD COLUMN retornou BOOLEAN,
    ADD COLUMN tipo_sistema VARCHAR(50),
    ADD COLUMN telhado VARCHAR(50),
    ADD COLUMN placas INTEGER,
    ADD COLUMN strings INTEGER,
    ADD COLUMN cabo_solar_verm_enviado DOUBLE PRECISION,
    ADD COLUMN cabo_solar_preto_enviado DOUBLE PRECISION,
    ADD COLUMN cabo_hepr_enviado DOUBLE PRECISION,
    ADD COLUMN cabo_solar_verm_devolvido DOUBLE PRECISION,
    ADD COLUMN cabo_solar_preto_devolvido DOUBLE PRECISION,
    ADD COLUMN cabo_hepr_devolvido DOUBLE PRECISION,
    ADD COLUMN cabo_solar_verm_usado DOUBLE PRECISION,
    ADD COLUMN cabo_solar_preto_usado DOUBLE PRECISION,
    ADD COLUMN cabo_hepr_usado DOUBLE PRECISION,
    ADD COLUMN qtd_materiais_enviados INTEGER,
    ADD COLUMN qtd_materiais_divergentes INTEGER,
    ADD COLUMN aproveitamento DOUBLE PRECISION,
    ADD COLUMN foto_sobras_grupo BOOLEAN,
    ADD COLUMN ajuste_fino DOUBLE PRECISION;
