ALTER TABLE lancamentos
    ADD COLUMN retornou BOOLEAN,
    ADD COLUMN tipo_sistema VARCHAR(50),
    ADD COLUMN telhado VARCHAR(50),
    ADD COLUMN placas INTEGER,
    ADD COLUMN strings INTEGER,
    ADD COLUMN cabo_solar_verm_enviado NUMERIC(10, 2),
    ADD COLUMN cabo_solar_preto_enviado NUMERIC(10, 2),
    ADD COLUMN cabo_hepr_enviado NUMERIC(10, 2),
    ADD COLUMN cabo_solar_verm_devolvido NUMERIC(10, 2),
    ADD COLUMN cabo_solar_preto_devolvido NUMERIC(10, 2),
    ADD COLUMN cabo_hepr_devolvido NUMERIC(10, 2),
    ADD COLUMN cabo_solar_verm_usado NUMERIC(10, 2),
    ADD COLUMN cabo_solar_preto_usado NUMERIC(10, 2),
    ADD COLUMN cabo_hepr_usado NUMERIC(10, 2),
    ADD COLUMN qtd_materiais_enviados INTEGER,
    ADD COLUMN qtd_materiais_divergentes INTEGER,
    ADD COLUMN aproveitamento NUMERIC(6, 4),
    ADD COLUMN foto_sobras_grupo BOOLEAN,
    ADD COLUMN ajuste_fino NUMERIC(10, 2);
